---
title: "Check the dispersion of a model"
author: "Thierry Onkelinx"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
set.seed(20181011)
```

## Generate data

```{r}
library(dplyr)
generate_data <- function(
  intercept = 0,
  sigma_random = 0.5,
  n_random = 20,
  n_replicate = 10,
  nb_size = 0.1,
  b_size = 5
) {
  re_random <- rnorm(n_random, mean = 0, sd = sigma_random)
  data.frame(
    id = rep(seq_len(n_random), n_replicate)
  ) %>%
    mutate(
      eta = intercept + re_random[id],
      poisson = rpois(n(), lambda = exp(eta)),
      negbin = rnbinom(n(), size = nb_size, mu = exp(eta)),
      binom = rbinom(n(), size = b_size, prob = plogis(eta))
    )  
}
dataset <- generate_data()
```


## Fit the models

```{r}
library(INLA)
poisson_model <- inla(
  poisson ~ 1 + f(id, model = "iid"), family = "poisson", 
  data = dataset, 
  control.compute = list(config = TRUE, waic = TRUE)
)
negbin_model <- inla(
  negbin ~ 1 + f(id, model = "iid"), family = "poisson", 
  data = dataset, 
  control.compute = list(config = TRUE, waic = TRUE)
)
binom_model <- inla(
  binom ~ 1 + f(id, model = "iid"), family = "poisson", 
  data = dataset, 
  control.compute = list(config = TRUE, waic = TRUE)
)
```

## Test the dispersion

```{r fig.cap = "Dispersion of the Poisson response"}
library(inlatools)
test_dispersion(poisson_model)
```

```{r, fig.cap = "Dispersion for the negative binomial response"}
test_dispersion(negbin_model)
```

```{r, fig.cap = "Dispersion for the negative binomial response"}
test_dispersion(binom_model)
```

## Simulation study

```{r eval = FALSE}
n_replicate <- 100
nsim <- 100

dispersion_poisson <- function(i, nsim = 100) {
  dataset <- generate_data()
  model <- inla(
    poisson ~ 1 + f(id, model = "iid"), family = "poisson", 
    data = dataset, 
    control.compute = list(config = TRUE, waic = TRUE)
  )
  D <- test_dispersion(model, nsim = nsim, plot = FALSE)
  mean(D$data > D$model)
}

dispersion_negbin <- function(i, nsim = 100) {
  dataset <- generate_data()
  model <- inla(
    negbin ~ 1 + f(id, model = "iid"), family = "poisson", 
    data = dataset, 
    control.compute = list(config = TRUE, waic = TRUE)
  )
  D <- test_dispersion(model, nsim = nsim, plot = FALSE)
  mean(D$data > D$model)
}

dispersion_binom <- function(i, nsim = 100) {
  dataset <- generate_data()
  model <- inla(
    binom ~ 1 + f(id, model = "iid"), family = "poisson", 
    data = dataset, 
    control.compute = list(config = TRUE, waic = TRUE)
  )
  D <- test_dispersion(model, nsim = nsim, plot = FALSE)
  mean(D$data > D$model)
}

library(purrr)
sim_dispersion_poisson <- map_dbl(
  seq_len(n_replicate), 
  dispersion_poisson,
  nsim = nsim
)
sim_dispersion_negbin <- map_dbl(
  seq_len(n_replicate), 
  dispersion_negbin,
  nsim = nsim
)
sim_dispersion_binom <- map_dbl(
  seq_len(n_replicate), 
  dispersion_binom,
  nsim = nsim
)

library(ggplot2)
data.frame(
  response = rep(
    c("Poisson", "negative\nbinomial", "binomial"), 
    each = n_replicate
  ),
  proportion = c(
    sim_dispersion_poisson, sim_dispersion_negbin, sim_dispersion_binom
  )
) %>%
  ggplot(aes(x = proportion)) +
  geom_density() +
  facet_wrap(~response, scales = "free_y")
```

